# Numpy ndarray &ndash; tieteellisen laskennan perusta Pythonissa

In [1]:
import numpy as np

## Tutkitaan numpy.ndarray:n ominaisuuksia

In [2]:
a = np.array([1,2,3,4,5], dtype='f8')
print(f'Taulukko: \n {a}')
print(f'Datatyyppi: {a.dtype}')
print(f'Muoto (\'shape\'): {a.shape}')
print(f'Askeleet (\'strides\'): {a.strides}')

Taulukko: 
 [1. 2. 3. 4. 5.]
Datatyyppi: float64
Muoto ('shape'): (5,)
Askeleet ('strides'): (8,)


In [3]:
b = np.array([1,2,3,4,5,6,7,8,9,10], dtype='i4').reshape(5,2)
print(f'Taulukko: \n {b}')
print(f'Datatyyppi: {b.dtype}')
print(f'Muoto (\'shape\'): {b.shape}')
print(f'Askeleet (\'strides\'): {b.strides}')

Taulukko: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Datatyyppi: int32
Muoto ('shape'): (5, 2)
Askeleet ('strides'): (8, 4)


## Indeksointi

In [4]:
a

array([1., 2., 3., 4., 5.])

In [5]:
b[4,1]

10

In [6]:
b[:,0]

array([1, 3, 5, 7, 9])

In [7]:
b[[2,3],[0,1]]

array([5, 8])

In [8]:
b[b>6]

array([ 7,  8,  9, 10])

## Vektorisointi ('vectorization') ja lähetys ('broadcasting')

In [9]:
c = a.reshape(5,1).copy()
print(c)
print(b)
print(c.shape)
print(b.shape)
c+b

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 1)
(5, 2)


array([[ 2.,  3.],
       [ 5.,  6.],
       [ 8.,  9.],
       [11., 12.],
       [14., 15.]])

## Taulukon kokoaminen ('reduction') (esim. np.sum, np.mean, np.median, np.std)

In [10]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
np.sum(b)

55

In [12]:
np.sum(b, axis=0)

array([25, 30])

In [13]:
np.sum(b, axis=1)

array([ 3,  7, 11, 15, 19])